[package]
name = "burrow-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "burrow-agent"
path = "src/main.rs"

[dependencies]
burrow-proto = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-vsock = { workspace = true }
tonic = { workspace = true }
nix = { workspace = true }
rtnetlink = { workspace = true }
netlink-packet-route = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
