# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_pb2 as api__pb2
from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BurrowStub(object):
    """Public control-plane API, served by burrow-orchestrator.
    Per-sandbox RPCs are routed to the node that owns the sandbox.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/burrow.api.v1.Burrow/Health',
                request_serializer=api__pb2.HealthRequest.SerializeToString,
                response_deserializer=api__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListNodes',
                request_serializer=api__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=api__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.DrainNode = channel.unary_unary(
                '/burrow.api.v1.Burrow/DrainNode',
                request_serializer=api__pb2.DrainNodeRequest.SerializeToString,
                response_deserializer=api__pb2.DrainNodeResponse.FromString,
                _registered_method=True)
        self.CreateSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/CreateSandbox',
                request_serializer=api__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/GetSandbox',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListSandboxes',
                request_serializer=api__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=api__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/DeleteSandbox',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=api__pb2.DeleteSandboxResponse.FromString,
                _registered_method=True)
        self.PauseSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/PauseSandbox',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.ResumeSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/ResumeSandbox',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListSessions',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=api__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.UpdateResources = channel.unary_unary(
                '/burrow.api.v1.Burrow/UpdateResources',
                request_serializer=api__pb2.UpdateResourcesRequest.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.ForkSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/ForkSandbox',
                request_serializer=api__pb2.ForkSandboxRequest.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.UpdateNetworkPolicy = channel.unary_unary(
                '/burrow.api.v1.Burrow/UpdateNetworkPolicy',
                request_serializer=api__pb2.UpdateNetworkPolicyRequest.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.UpdateTags = channel.unary_unary(
                '/burrow.api.v1.Burrow/UpdateTags',
                request_serializer=api__pb2.UpdateTagsRequest.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.UpdateAccessPolicy = channel.unary_unary(
                '/burrow.api.v1.Burrow/UpdateAccessPolicy',
                request_serializer=api__pb2.UpdateAccessPolicyRequest.SerializeToString,
                response_deserializer=common__pb2.Sandbox.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/burrow.api.v1.Burrow/CreateSnapshot',
                request_serializer=api__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=common__pb2.Snapshot.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListSnapshots',
                request_serializer=api__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=api__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/burrow.api.v1.Burrow/GetSnapshot',
                request_serializer=api__pb2.SnapshotRef.SerializeToString,
                response_deserializer=common__pb2.Snapshot.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/burrow.api.v1.Burrow/DeleteSnapshot',
                request_serializer=api__pb2.SnapshotRef.SerializeToString,
                response_deserializer=api__pb2.DeleteSnapshotResponse.FromString,
                _registered_method=True)
        self.CreateVolume = channel.unary_unary(
                '/burrow.api.v1.Burrow/CreateVolume',
                request_serializer=api__pb2.CreateVolumeRequest.SerializeToString,
                response_deserializer=common__pb2.Volume.FromString,
                _registered_method=True)
        self.ListVolumes = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListVolumes',
                request_serializer=api__pb2.ListVolumesRequest.SerializeToString,
                response_deserializer=api__pb2.ListVolumesResponse.FromString,
                _registered_method=True)
        self.GetVolume = channel.unary_unary(
                '/burrow.api.v1.Burrow/GetVolume',
                request_serializer=api__pb2.VolumeRef.SerializeToString,
                response_deserializer=common__pb2.Volume.FromString,
                _registered_method=True)
        self.DeleteVolume = channel.unary_unary(
                '/burrow.api.v1.Burrow/DeleteVolume',
                request_serializer=api__pb2.VolumeRef.SerializeToString,
                response_deserializer=api__pb2.DeleteVolumeResponse.FromString,
                _registered_method=True)
        self.Exec = channel.stream_stream(
                '/burrow.api.v1.Burrow/Exec',
                request_serializer=api__pb2.ExecInput.SerializeToString,
                response_deserializer=api__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.ListCommands = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListCommands',
                request_serializer=api__pb2.ListCommandsRequest.SerializeToString,
                response_deserializer=api__pb2.ListCommandsResponse.FromString,
                _registered_method=True)
        self.GetCommand = channel.unary_unary(
                '/burrow.api.v1.Burrow/GetCommand',
                request_serializer=api__pb2.GetCommandRequest.SerializeToString,
                response_deserializer=api__pb2.CommandInfo.FromString,
                _registered_method=True)
        self.AttachCommand = channel.unary_stream(
                '/burrow.api.v1.Burrow/AttachCommand',
                request_serializer=api__pb2.AttachCommandRequest.SerializeToString,
                response_deserializer=api__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.SignalCommand = channel.unary_unary(
                '/burrow.api.v1.Burrow/SignalCommand',
                request_serializer=api__pb2.SignalCommandRequest.SerializeToString,
                response_deserializer=api__pb2.SignalCommandResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/burrow.api.v1.Burrow/CreateUser',
                request_serializer=api__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=api__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/burrow.api.v1.Burrow/CreateGroup',
                request_serializer=api__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=api__pb2.CreateGroupResponse.FromString,
                _registered_method=True)
        self.AddUserToGroup = channel.unary_unary(
                '/burrow.api.v1.Burrow/AddUserToGroup',
                request_serializer=api__pb2.GroupMembershipRequest.SerializeToString,
                response_deserializer=api__pb2.GroupMembershipResponse.FromString,
                _registered_method=True)
        self.RemoveUserFromGroup = channel.unary_unary(
                '/burrow.api.v1.Burrow/RemoveUserFromGroup',
                request_serializer=api__pb2.GroupMembershipRequest.SerializeToString,
                response_deserializer=api__pb2.GroupMembershipResponse.FromString,
                _registered_method=True)
        self.BuildTemplate = channel.unary_stream(
                '/burrow.api.v1.Burrow/BuildTemplate',
                request_serializer=api__pb2.BuildTemplateRequest.SerializeToString,
                response_deserializer=api__pb2.BuildLog.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListTemplates',
                request_serializer=api__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=api__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.DeleteTemplate = channel.unary_unary(
                '/burrow.api.v1.Burrow/DeleteTemplate',
                request_serializer=api__pb2.DeleteTemplateRequest.SerializeToString,
                response_deserializer=api__pb2.DeleteTemplateResponse.FromString,
                _registered_method=True)
        self.ExposePort = channel.unary_unary(
                '/burrow.api.v1.Burrow/ExposePort',
                request_serializer=api__pb2.ExposePortRequest.SerializeToString,
                response_deserializer=api__pb2.PortMapping.FromString,
                _registered_method=True)
        self.ListPorts = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListPorts',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=api__pb2.ListPortsResponse.FromString,
                _registered_method=True)
        self.ClosePort = channel.unary_unary(
                '/burrow.api.v1.Burrow/ClosePort',
                request_serializer=api__pb2.ClosePortRequest.SerializeToString,
                response_deserializer=api__pb2.ClosePortResponse.FromString,
                _registered_method=True)
        self.ShareSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/ShareSandbox',
                request_serializer=api__pb2.ShareRequest.SerializeToString,
                response_deserializer=api__pb2.Share.FromString,
                _registered_method=True)
        self.GetShare = channel.unary_unary(
                '/burrow.api.v1.Burrow/GetShare',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=api__pb2.Share.FromString,
                _registered_method=True)
        self.UnshareSandbox = channel.unary_unary(
                '/burrow.api.v1.Burrow/UnshareSandbox',
                request_serializer=api__pb2.SandboxRef.SerializeToString,
                response_deserializer=api__pb2.UnshareResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/burrow.api.v1.Burrow/UploadFile',
                request_serializer=api__pb2.FileChunk.SerializeToString,
                response_deserializer=api__pb2.UploadResult.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/burrow.api.v1.Burrow/DownloadFile',
                request_serializer=api__pb2.DownloadRequest.SerializeToString,
                response_deserializer=api__pb2.FileChunk.FromString,
                _registered_method=True)
        self.ListDir = channel.unary_unary(
                '/burrow.api.v1.Burrow/ListDir',
                request_serializer=api__pb2.ListDirRequest.SerializeToString,
                response_deserializer=api__pb2.ListDirResponse.FromString,
                _registered_method=True)
        self.QueryAudit = channel.unary_stream(
                '/burrow.api.v1.Burrow/QueryAudit',
                request_serializer=api__pb2.AuditQuery.SerializeToString,
                response_deserializer=api__pb2.AuditEvent.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/burrow.api.v1.Burrow/Watch',
                request_serializer=api__pb2.WatchRequest.SerializeToString,
                response_deserializer=api__pb2.WatchEvent.FromString,
                _registered_method=True)


class BurrowServicer(object):
    """Public control-plane API, served by burrow-orchestrator.
    Per-sandbox RPCs are routed to the node that owns the sandbox.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainNode(self, request, context):
        """Stop placing new sandboxes on a node, optionally suspending what it runs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSandbox(self, request, context):
        """Sandboxes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Every VM this sandbox has run, newest first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResources(self, request, context):
        """Move the clocks a running sandbox is measured against: lifetime, idle
        suspension and suspended retention. The machine shape is not movable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkSandbox(self, request, context):
        """Create a sandbox from another's current state, on the source's node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNetworkPolicy(self, request, context):
        """Replace a running sandbox's egress policy: firewall rules, proxy
        allowlist, DNS filtering and header injection all re-render at once.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTags(self, request, context):
        """Replace a sandbox's tags wholesale.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccessPolicy(self, request, context):
        """Replace a live sandbox's exec and file policies. Enforced on the node, so
        the change is in force on the next call without disturbing the guest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Snapshots: a sandbox's state, kept as an object of its own.

        Node-local, like templates: a snapshot can only be restored on the node
        that took it, so a create from one is placed there.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVolume(self, request, context):
        """Volumes: persistent storage, mounted into sandboxes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVolumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request_iterator, context):
        """Exec: bidirectional stream, PTY-capable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCommands(self, request, context):
        """Commands: a command outlives the stream that started it, so it can be
        listed, followed and signalled from another process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Users and groups inside the guest. Each runs a command in the sandbox, so
        all four are held to the sandbox's exec policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildTemplate(self, request, context):
        """Templates: build a reusable guest image by running steps in a sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExposePort(self, request, context):
        """Ports: publish a guest port on the node's address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPorts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClosePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareSandbox(self, request, context):
        """Shares: reach a sandbox's ports through a tailcat address, a WireGuard
        tunnel bootstrapped over a DERP relay. No host port, no edge, and the
        connection wakes a suspended sandbox. The address is the credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnshareSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAudit(self, request, context):
        """Audit: every egress attempt and DNS lookup a sandbox made.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BurrowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=api__pb2.HealthRequest.FromString,
                    response_serializer=api__pb2.HealthResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=api__pb2.ListNodesRequest.FromString,
                    response_serializer=api__pb2.ListNodesResponse.SerializeToString,
            ),
            'DrainNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainNode,
                    request_deserializer=api__pb2.DrainNodeRequest.FromString,
                    response_serializer=api__pb2.DrainNodeResponse.SerializeToString,
            ),
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=api__pb2.CreateSandboxRequest.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=api__pb2.ListSandboxesRequest.FromString,
                    response_serializer=api__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=api__pb2.DeleteSandboxResponse.SerializeToString,
            ),
            'PauseSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSandbox,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'ResumeSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSandbox,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=api__pb2.ListSessionsResponse.SerializeToString,
            ),
            'UpdateResources': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResources,
                    request_deserializer=api__pb2.UpdateResourcesRequest.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'ForkSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkSandbox,
                    request_deserializer=api__pb2.ForkSandboxRequest.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'UpdateNetworkPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNetworkPolicy,
                    request_deserializer=api__pb2.UpdateNetworkPolicyRequest.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'UpdateTags': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTags,
                    request_deserializer=api__pb2.UpdateTagsRequest.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'UpdateAccessPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccessPolicy,
                    request_deserializer=api__pb2.UpdateAccessPolicyRequest.FromString,
                    response_serializer=common__pb2.Sandbox.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=api__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=common__pb2.Snapshot.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=api__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=api__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=api__pb2.SnapshotRef.FromString,
                    response_serializer=common__pb2.Snapshot.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=api__pb2.SnapshotRef.FromString,
                    response_serializer=api__pb2.DeleteSnapshotResponse.SerializeToString,
            ),
            'CreateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVolume,
                    request_deserializer=api__pb2.CreateVolumeRequest.FromString,
                    response_serializer=common__pb2.Volume.SerializeToString,
            ),
            'ListVolumes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVolumes,
                    request_deserializer=api__pb2.ListVolumesRequest.FromString,
                    response_serializer=api__pb2.ListVolumesResponse.SerializeToString,
            ),
            'GetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolume,
                    request_deserializer=api__pb2.VolumeRef.FromString,
                    response_serializer=common__pb2.Volume.SerializeToString,
            ),
            'DeleteVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVolume,
                    request_deserializer=api__pb2.VolumeRef.FromString,
                    response_serializer=api__pb2.DeleteVolumeResponse.SerializeToString,
            ),
            'Exec': grpc.stream_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=api__pb2.ExecInput.FromString,
                    response_serializer=api__pb2.ExecOutput.SerializeToString,
            ),
            'ListCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCommands,
                    request_deserializer=api__pb2.ListCommandsRequest.FromString,
                    response_serializer=api__pb2.ListCommandsResponse.SerializeToString,
            ),
            'GetCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommand,
                    request_deserializer=api__pb2.GetCommandRequest.FromString,
                    response_serializer=api__pb2.CommandInfo.SerializeToString,
            ),
            'AttachCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.AttachCommand,
                    request_deserializer=api__pb2.AttachCommandRequest.FromString,
                    response_serializer=api__pb2.ExecOutput.SerializeToString,
            ),
            'SignalCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalCommand,
                    request_deserializer=api__pb2.SignalCommandRequest.FromString,
                    response_serializer=api__pb2.SignalCommandResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=api__pb2.CreateUserRequest.FromString,
                    response_serializer=api__pb2.CreateUserResponse.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=api__pb2.CreateGroupRequest.FromString,
                    response_serializer=api__pb2.CreateGroupResponse.SerializeToString,
            ),
            'AddUserToGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToGroup,
                    request_deserializer=api__pb2.GroupMembershipRequest.FromString,
                    response_serializer=api__pb2.GroupMembershipResponse.SerializeToString,
            ),
            'RemoveUserFromGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromGroup,
                    request_deserializer=api__pb2.GroupMembershipRequest.FromString,
                    response_serializer=api__pb2.GroupMembershipResponse.SerializeToString,
            ),
            'BuildTemplate': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildTemplate,
                    request_deserializer=api__pb2.BuildTemplateRequest.FromString,
                    response_serializer=api__pb2.BuildLog.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=api__pb2.ListTemplatesRequest.FromString,
                    response_serializer=api__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'DeleteTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTemplate,
                    request_deserializer=api__pb2.DeleteTemplateRequest.FromString,
                    response_serializer=api__pb2.DeleteTemplateResponse.SerializeToString,
            ),
            'ExposePort': grpc.unary_unary_rpc_method_handler(
                    servicer.ExposePort,
                    request_deserializer=api__pb2.ExposePortRequest.FromString,
                    response_serializer=api__pb2.PortMapping.SerializeToString,
            ),
            'ListPorts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPorts,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=api__pb2.ListPortsResponse.SerializeToString,
            ),
            'ClosePort': grpc.unary_unary_rpc_method_handler(
                    servicer.ClosePort,
                    request_deserializer=api__pb2.ClosePortRequest.FromString,
                    response_serializer=api__pb2.ClosePortResponse.SerializeToString,
            ),
            'ShareSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareSandbox,
                    request_deserializer=api__pb2.ShareRequest.FromString,
                    response_serializer=api__pb2.Share.SerializeToString,
            ),
            'GetShare': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShare,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=api__pb2.Share.SerializeToString,
            ),
            'UnshareSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.UnshareSandbox,
                    request_deserializer=api__pb2.SandboxRef.FromString,
                    response_serializer=api__pb2.UnshareResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=api__pb2.FileChunk.FromString,
                    response_serializer=api__pb2.UploadResult.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=api__pb2.DownloadRequest.FromString,
                    response_serializer=api__pb2.FileChunk.SerializeToString,
            ),
            'ListDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDir,
                    request_deserializer=api__pb2.ListDirRequest.FromString,
                    response_serializer=api__pb2.ListDirResponse.SerializeToString,
            ),
            'QueryAudit': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryAudit,
                    request_deserializer=api__pb2.AuditQuery.FromString,
                    response_serializer=api__pb2.AuditEvent.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=api__pb2.WatchRequest.FromString,
                    response_serializer=api__pb2.WatchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'burrow.api.v1.Burrow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('burrow.api.v1.Burrow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Burrow(object):
    """Public control-plane API, served by burrow-orchestrator.
    Per-sandbox RPCs are routed to the node that owns the sandbox.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/Health',
            api__pb2.HealthRequest.SerializeToString,
            api__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListNodes',
            api__pb2.ListNodesRequest.SerializeToString,
            api__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/DrainNode',
            api__pb2.DrainNodeRequest.SerializeToString,
            api__pb2.DrainNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/CreateSandbox',
            api__pb2.CreateSandboxRequest.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/GetSandbox',
            api__pb2.SandboxRef.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListSandboxes',
            api__pb2.ListSandboxesRequest.SerializeToString,
            api__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/DeleteSandbox',
            api__pb2.SandboxRef.SerializeToString,
            api__pb2.DeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/PauseSandbox',
            api__pb2.SandboxRef.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ResumeSandbox',
            api__pb2.SandboxRef.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListSessions',
            api__pb2.SandboxRef.SerializeToString,
            api__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/UpdateResources',
            api__pb2.UpdateResourcesRequest.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ForkSandbox',
            api__pb2.ForkSandboxRequest.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNetworkPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/UpdateNetworkPolicy',
            api__pb2.UpdateNetworkPolicyRequest.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/UpdateTags',
            api__pb2.UpdateTagsRequest.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccessPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/UpdateAccessPolicy',
            api__pb2.UpdateAccessPolicyRequest.SerializeToString,
            common__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/CreateSnapshot',
            api__pb2.CreateSnapshotRequest.SerializeToString,
            common__pb2.Snapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListSnapshots',
            api__pb2.ListSnapshotsRequest.SerializeToString,
            api__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/GetSnapshot',
            api__pb2.SnapshotRef.SerializeToString,
            common__pb2.Snapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/DeleteSnapshot',
            api__pb2.SnapshotRef.SerializeToString,
            api__pb2.DeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/CreateVolume',
            api__pb2.CreateVolumeRequest.SerializeToString,
            common__pb2.Volume.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVolumes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListVolumes',
            api__pb2.ListVolumesRequest.SerializeToString,
            api__pb2.ListVolumesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/GetVolume',
            api__pb2.VolumeRef.SerializeToString,
            common__pb2.Volume.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/DeleteVolume',
            api__pb2.VolumeRef.SerializeToString,
            api__pb2.DeleteVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/burrow.api.v1.Burrow/Exec',
            api__pb2.ExecInput.SerializeToString,
            api__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListCommands',
            api__pb2.ListCommandsRequest.SerializeToString,
            api__pb2.ListCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/GetCommand',
            api__pb2.GetCommandRequest.SerializeToString,
            api__pb2.CommandInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/burrow.api.v1.Burrow/AttachCommand',
            api__pb2.AttachCommandRequest.SerializeToString,
            api__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/SignalCommand',
            api__pb2.SignalCommandRequest.SerializeToString,
            api__pb2.SignalCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/CreateUser',
            api__pb2.CreateUserRequest.SerializeToString,
            api__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/CreateGroup',
            api__pb2.CreateGroupRequest.SerializeToString,
            api__pb2.CreateGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUserToGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/AddUserToGroup',
            api__pb2.GroupMembershipRequest.SerializeToString,
            api__pb2.GroupMembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/RemoveUserFromGroup',
            api__pb2.GroupMembershipRequest.SerializeToString,
            api__pb2.GroupMembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/burrow.api.v1.Burrow/BuildTemplate',
            api__pb2.BuildTemplateRequest.SerializeToString,
            api__pb2.BuildLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListTemplates',
            api__pb2.ListTemplatesRequest.SerializeToString,
            api__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/DeleteTemplate',
            api__pb2.DeleteTemplateRequest.SerializeToString,
            api__pb2.DeleteTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExposePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ExposePort',
            api__pb2.ExposePortRequest.SerializeToString,
            api__pb2.PortMapping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPorts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListPorts',
            api__pb2.SandboxRef.SerializeToString,
            api__pb2.ListPortsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClosePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ClosePort',
            api__pb2.ClosePortRequest.SerializeToString,
            api__pb2.ClosePortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ShareSandbox',
            api__pb2.ShareRequest.SerializeToString,
            api__pb2.Share.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/GetShare',
            api__pb2.SandboxRef.SerializeToString,
            api__pb2.Share.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnshareSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/UnshareSandbox',
            api__pb2.SandboxRef.SerializeToString,
            api__pb2.UnshareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/burrow.api.v1.Burrow/UploadFile',
            api__pb2.FileChunk.SerializeToString,
            api__pb2.UploadResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/burrow.api.v1.Burrow/DownloadFile',
            api__pb2.DownloadRequest.SerializeToString,
            api__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/burrow.api.v1.Burrow/ListDir',
            api__pb2.ListDirRequest.SerializeToString,
            api__pb2.ListDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/burrow.api.v1.Burrow/QueryAudit',
            api__pb2.AuditQuery.SerializeToString,
            api__pb2.AuditEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/burrow.api.v1.Burrow/Watch',
            api__pb2.WatchRequest.SerializeToString,
            api__pb2.WatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
